package com.kumarkd2x.vibeplay.data.model

/**
 * Video Model
 *
 * Ye data classes YouTube video ka data represent karti hain.
 * Piped API se JSON aayega aur ye models me convert hoga.
 */

// ==================== VIDEO ====================
data class Video(
    val id: String,
    val title: String,
    val description: String = "",
    val thumbnailUrl: String,
    val duration: Int = 0,           // seconds me
    val views: Long = 0,
    val uploadedDate: String = "",
    val channelName: String = "",
    val channelAvatarUrl: String = "",
    val channelId: String = "",
    val uploaderVerified: Boolean = false
) {
    /** Duration ko "MM:SS" ya "H:MM:SS" format me convert karta hai */
    fun getFormattedDuration(): String {
        if (duration <= 0) return "00:00"
        val hours = duration / 3600
        val minutes = (duration % 3600) / 60
        val seconds = duration % 60
        return if (hours > 0) {
            String.format("%d:%02d:%02d", hours, minutes, seconds)
        } else {
            String.format("%02d:%02d", minutes, seconds)
        }
    }

    /** Views ko "1.2M", "500K" format me convert karta hai */
    fun getFormattedViews(): String {
        return when {
            views >= 1_000_000_000 -> String.format("%.1fB", views / 1_000_000_000.0)
            views >= 1_000_000 -> String.format("%.1fM", views / 1_000_000.0)
            views >= 1_000 -> String.format("%.1fK", views / 1_000.0)
            else -> views.toString()
        }
    }
}

// ==================== STREAM INFO ====================
data class StreamInfo(
    val url: String,
    val quality: String,        // "1080p", "720p", "480p", etc.
    val mimeType: String,       // "video/mp4", "audio/mp4"
    val bitrate: Int = 0,
    val isVideo: Boolean = true,
    val isAudio: Boolean = false
)

// ==================== AUDIO STREAM ====================
data class AudioStream(
    val url: String,
    val quality: String,        // "128kbps", "320kbps"
    val mimeType: String
)

// ==================== SUBTITLE ====================
data class Subtitle(
    val url: String,
    val language: String,
    val languageCode: String,   // "en", "hi", "es"
    val isAutoGenerated: Boolean = false
)

// ==================== VIDEO DETAILS ====================
data class VideoDetails(
    val video: Video,
    val videoStreams: List<StreamInfo> = emptyList(),
    val audioStreams: List<AudioStream> = emptyList(),
    val subtitles: List<Subtitle> = emptyList(),
    val relatedVideos: List<Video> = emptyList(),
    val hlsUrl: String = "",
    val dashUrl: String = ""
)

// ==================== SEARCH FILTER ====================
enum class SearchFilter(val value: String) {
    ALL("all"),
    VIDEOS("videos"),
    CHANNELS("channels"),
    PLAYLISTS("playlists"),
    MUSIC_SONGS("music_songs"),
    MUSIC_VIDEOS("music_videos"),
    MUSIC_ALBUMS("music_albums")
}

// ==================== TRENDING ====================
// Trending koi special class nahi, bas List<Video> hai

// ==================== HISTORY ENTRY ====================
data class WatchHistoryEntry(
    val video: Video,
    val watchedAt: Long = System.currentTimeMillis(),
    val positionMs: Long = 0L,
    val durationMs: Long = 0L
)

// ==================== BOOKMARK ====================
data class Bookmark(
    val id: Long = 0,
    val videoId: String,
    val videoTitle: String,
    val timestampMs: Long,
    val note: String = "",
    val createdAt: Long = System.currentTimeMillis()
)
